spring:
  profiles:
    active: usage_message
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  data:
    mongodb:
      uri: mongodb://localhost:27017/test_docs

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 100000
